#SERVER PORT
server:
  port: 9004

#SPRING DEVTOOLS
spring:
  devtools:
    restart:
      exclude: static/**,public/**

#MULTIPART FILE CONFIGURATION
  servlet:
    multipart:
      max-file-size: 524288000
      max-request-size: 524288000

  #SPRING APPLICATION NAME
  application:
    name: dds2-rest-be-v1

  #SPRING DATASOURCE CONFIGURATION
  datasource:
    url: jdbc:postgresql://localhost:5432/DSS_DB_V1
    username: postgres
    password: password

  #JPA AND HIBERNATE PROPERTIES
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc:
          timezone: GMT+8
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

#SLF4J LOGBACK CONFIGURATION
logging:
  level:
    root: error
    org.springframework: debug
    org.hibernate: error

# REGISTER WITH EUREKA
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

dss-file-path: C:\applogs\image\