server:
  port: 9096

spring:
  application:
    name: dd4-ms-movie-v1

# register with eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost